openapi: 3.0.1
info:
  title: Achievements API
  version: 1.0.0
  description: API для работы с достижениями пользователей

paths:
  /api/v1/achievements:
    get:
      summary: Получить все достижения
      description: Возвращает список всех доступных достижений
      tags:
        - Achievements
      responses:
        '200':
          description: Список достижений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Achievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/my:
    get:
      summary: Получить достижения пользователя
      description: Возвращает достижения текущего пользователя, разделенные на завершенные и в процессе
      tags:
        - Achievements
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Достижения пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                  completed:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
                  in_progress:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/by_category:
    get:
      summary: Получить достижения по категории
      description: Возвращает достижения определенной категории
      tags:
        - Achievements
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
            enum:
              [
                registration,
                content_viewing,
                dev_diving,
                legacy,
                it_errors,
                it_security,
                general
              ]
          description: Категория достижений
      responses:
        '200':
          description: Достижения по категории
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Achievement'
        '400':
          description: Неверная категория
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  schemas:
    Achievement:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор достижения
        name:
          type: string
          description: Название достижения
        description:
          type: string
          description: Описание достижения
        category:
          type: string
          enum:
            [
              registration,
              content_viewing,
              dev_diving,
              legacy,
              it_errors,
              it_security,
              general
            ]
          description: |
            Категория достижения:
            - registration, content_viewing - специальные достижения
            - dev_diving, legacy, it_errors, it_security - темы контента
            - general - общие достижения (собирают интерактивы со всех тем)
        progress_type:
          type: string
          enum:
            [
              consecutive_days,
              total_interactives,
              registration_order,
              platform_lifetime
            ]
          description: Тип прогресса
        progress_target:
          type: integer
          description: Целевое значение для завершения
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    UserAchievement:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор пользовательского достижения
        achievement:
          $ref: '#/components/schemas/Achievement'
        progress:
          type: integer
          description: Текущий прогресс
        progress_percentage:
          type: integer
          description: Процент выполнения (0-100)
        completed_at:
          type: string
          format: date-time
          nullable: true
          description: Дата завершения достижения
        completed:
          type: boolean
          description: Завершено ли достижение

  responses:
    UnauthorizedError:
      description: Неавторизованный доступ
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Unauthorized'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
