openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /api/v1/health:
    get:
      tags:
        - Health
      summary: Health check endpoint
      description: Returns the health status of the API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    example: '2023-01-01T00:00:00Z'

  /api/v1/auth:
    post:
      tags:
        - Authentication
      summary: Login or Register
      description: Авторизация или регистрация пользователя. Если пользователь с таким email существует - проверяет пароль, если нет - создает нового пользователя.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 6
                  example: password123
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Успешный вход
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQwNzI4MDB9.example
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: user@example.com
        '201':
          description: Пользователь зарегистрирован, требуется подтверждение email
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Пользователь зарегистрирован. Проверьте email для подтверждения.
                  requires_verification:
                    type: boolean
                    example: true
                  email:
                    type: string
                    example: user@example.com
        '400':
          description: Неверные входные данные
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Email и пароль обязательны
        '401':
          description: Неверный пароль
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Неверный пароль
        '422':
          description: Ошибка регистрации
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Ошибка регистрации
                  details:
                    type: array
                    items:
                      type: string
                    example: ['Email has already been taken']
        '403':
          description: Email не подтвержден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Email не подтвержден
                  requires_verification:
                    type: boolean
                    example: true
                  email:
                    type: string
                    example: user@example.com

  /api/v1/auth/verify:
    post:
      tags:
        - Authentication
      summary: Подтверждение email
      description: Подтверждение email с помощью 6-значного кода
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                code:
                  type: string
                  pattern: '^[0-9]{6}$'
                  example: '123456'
      responses:
        '200':
          description: Email успешно подтвержден
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email успешно подтвержден
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQwNzI4MDB9.example
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: user@example.com
        '400':
          description: Неверные входные данные
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Email и код обязательны
        '401':
          description: Неверный или истекший код
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Неверный или истекший код
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Пользователь не найден

  /api/v1/auth/resend:
    post:
      tags:
        - Authentication
      summary: Повторная отправка кода
      description: Отправка нового кода подтверждения на email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '200':
          description: Код отправлен повторно
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Код подтверждения отправлен повторно
        '400':
          description: Неверные входные данные
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Email обязателен
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Пользователь не найден

  /api/v1/auth/supported-domains:
    get:
      tags:
        - Authentication
      summary: Поддерживаемые домены
      description: Получить список поддерживаемых почтовых доменов
      responses:
        '200':
          description: Список поддерживаемых доменов
          content:
            application/json:
              schema:
                type: object
                properties:
                  supported_domains:
                    type: array
                    items:
                      type: string
                    example:
                      ['gmail.com', 'yandex.ru', 'mail.ru', 'outlook.com']
                  message:
                    type: string
                    example: Поддерживаемые почтовые домены для регистрации

  /api/v1/auth/me:
    get:
      tags:
        - Authentication
      summary: Get current user info
      description: Получить информацию о текущем авторизованном пользователе
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Информация о пользователе
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: user@example.com
        '401':
          description: Требуется авторизация
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Требуется авторизация

  /api/v1/achievements:
    get:
      tags:
        - Achievements
      summary: Получить все достижения
      description: Возвращает список всех доступных достижений
      responses:
        '200':
          description: Список достижений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Achievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/my:
    get:
      tags:
        - Achievements
      summary: Получить достижения пользователя
      description: Возвращает достижения текущего пользователя, разделенные на завершенные и в процессе
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Достижения пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                  completed:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
                  in_progress:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/by_category:
    get:
      tags:
        - Achievements
      summary: Получить достижения по категории
      description: Возвращает достижения определенной категории
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
            enum:
              [
                registration,
                content_viewing,
                dev_diving,
                legacy,
                it_errors,
                it_security,
                general
              ]
          description: Категория достижений
      responses:
        '200':
          description: Достижения по категории
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Achievement'
        '400':
          description: Неверная категория
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/test/interactive:
    post:
      tags:
        - Achievements
      summary: Тест прохождения интерактива
      description: Симулирует прохождение интерактива для проверки системы достижений
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content_category:
                  type: string
                  enum: [dev_diving, legacy, it_errors, it_security]
                  default: dev_diving
                  description: Тема контента
      responses:
        '200':
          description: Достижения обновлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updated_achievements:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/test/consecutive_days:
    post:
      tags:
        - Achievements
      summary: Тест дней подряд
      description: Симулирует просмотр контента подряд для проверки системы достижений
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                days:
                  type: integer
                  default: 7
                  description: Количество дней подряд
      responses:
        '200':
          description: Достижения обновлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updated_achievements:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/achievements/test/registration:
    post:
      tags:
        - Achievements
      summary: Тест достижений по регистрации
      description: Симулирует проверку достижений по порядку регистрации пользователя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Достижения обновлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updated_achievements:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAchievement'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  schemas:
    Achievement:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор достижения
        name:
          type: string
          description: Название достижения
        description:
          type: string
          description: Описание достижения
        category:
          type: string
          enum:
            [
              registration,
              content_viewing,
              dev_diving,
              legacy,
              it_errors,
              it_security,
              general
            ]
          description: |
            Категория достижения:
            - registration, content_viewing - специальные достижения
            - dev_diving, legacy, it_errors, it_security - темы контента
            - general - общие достижения (собирают интерактивы со всех тем)
        progress_type:
          type: string
          enum:
            [
              consecutive_days,
              total_interactives,
              registration_order,
              platform_lifetime
            ]
          description: Тип прогресса
        progress_target:
          type: integer
          description: Целевое значение для завершения
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    UserAchievement:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор пользовательского достижения
        achievement:
          $ref: '#/components/schemas/Achievement'
        progress:
          type: integer
          description: Текущий прогресс
        progress_percentage:
          type: integer
          description: Процент выполнения (0-100)
        completed_at:
          type: string
          format: date-time
          nullable: true
          description: Дата завершения достижения
        completed:
          type: boolean
          description: Завершено ли достижение

  responses:
    UnauthorizedError:
      description: Неавторизованный доступ
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Unauthorized'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3000
    description: Development server
